config/routes.rb
Rails.application.routes.draw do

  get 'backoffice', to: 'backoffice/dashboard#index'
  
  namespace :backoffice do
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]
    get 'dashboard', to: 'dashboard#index'
    post 'dashboard/set_ano' , :defaults => { :format => 'json' }
  end
  namespace :site do
    get 'home', to: 'home#index'
  end  

  devise_for :admins, :skip => [:registrations]
  devise_for :members

  root 'site/home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :category
  belongs_to :member
end

app/models/admin.rb
class Admin < ApplicationRecord
  enum role: [:full_access, :restricted_access]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def role_br
    if self.role == 'full_access'
      "Acesso Completo"
    else
      "Acesso Restrito"
    end
    
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    validates_presence_of :description
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    layout :layout_by_resource

    protected
    def layout_by_resource
        if devise_controller? && resource_name == :admin
          "backoffice_devise"
        else
          "application"
        end
      end
end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]
  def index
    @admins = Admin.all
  end

  def new
    @admin = Admin.new    
  end

  def edit
  end

  def destroy
    admin_email = @admin.email
    if @admin.destroy
      redirect_to backoffice_admins_path, alert: "O admin (#{admin_email}) foi excluído com sucesso"
    else
      render :index
    end
  end

  def update
    passwd = params[:admin][:password]
    passwd_confirmation = params[:admin][:password_confirmation]

    if passwd.blank? && passwd_confirmation.blank?
      params[:admin].delete(:password)
      params[:admin].delete(:password_confirmation)
    end

    if @admin.update(params_admin)
      redirect_to backoffice_admins_path, alert: "O admin (#{@admin.email}) foi atualizada com sucesso"
    else
      render :edit
    end
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to backoffice_admins_path, alert: "O admin (#{@admin.email}) foi cadastrada com sucesso"
    else
      render :new
    end
  end

  private

  def set_admin
    @admin = Admin.find(params[:id]) 
  end

  def params_admin
    params.require(:admin).permit(:name, :role, :email, :password, :password_confirmation)
  end

end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  before_action :set_category, only: [:edit, :update]
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new    
  end

  def edit
  end

  def update
    if @category.update(params_category)
      redirect_to backoffice_categories_path, alert: "A categoria (#{@category.description}) foi atualizada com sucesso"
    else
      render :edit
    end
  end

  def create
    @category = Category.new(params_category)
    if @category.save
      redirect_to backoffice_categories_path, alert: "A categoria (#{@category.description}) foi cadastrada com sucesso"
    else
      render :new
    end
  end

  private

  def set_category
    @category = Category.find(params[:id]) 
  end

  def params_category
    params.require(:category).permit(:description)
  end

end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController
  def index
    puts '------------inicial----------------'
    puts session[:ano]
  end

  def set_ano
    session[:ano] = params[:ano]
    puts '---------------session-----------------------'
    puts session[:ano]
    render :json => {:msg => "Ano base alterado para #{params[:ano]}"}
   end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
    before_action :authenticate_admin!
    layout "backoffice"
end

app/controllers/site/home_controller.rb
class Site::HomeController < ApplicationController
  layout "site"
  def index
    @categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/backoffice/admins/index.html.erb
<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Listando Aministradores</h1>            
            </div>
            <!-- /.col-lg-12 -->
        </div>
        
        <!-- /.row -->
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nome</th>
                        <th>Email</th>
                        <th>Tipo de acesso</th>
                        <th></th>
                    </tr>
                </thead>
                
                <tbody>
                <% @admins.each do |admin| %>
                    <tr>
                        <td><%= admin.id %></td>
                        <td><%= admin.name %></td>
                        <td><%= admin.email %></td>
                        <td><%= admin.role_br %></td>
                        <td style = "width: 150px">
                            <%= link_to edit_backoffice_admin_path(admin), class: "btn btn-primary btn-circle" do %>
                                <i class="fa fa-edit"></i>
                            <% end %>

                            <% if current_admin.id != admin.id %>
                                <%= link_to backoffice_admin_path(admin), method: :delete, class: "btn btn-danger btn-circle",
                                data: {confirm: "Você deseja realmente excluir #{admin.email}?"} do %>
                                <i class="fa fa-times"></i>
                                <% end %>
                            <% end %>
                        </td>
                    </tr>                  
                <% end %>                    
                </tbody>
            </table>
        </div>
        <div class="row">
            <%= link_to new_backoffice_admin_path, class: "btn btn-success btn-circle pull-right" do %>
                <i class="fa fa-plus"></i>
            <% end %>
        </div>

    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->>
 

app/views/backoffice/categories/edit.html.erb
<%= render partial: "backoffice/categories/shared/form", locals: {action: "Editando categoria"} %>

app/views/backoffice/categories/index.html.erb
<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Listando Categorias</h1>            
            </div>
            <!-- /.col-lg-12 -->
        </div>
        
        <!-- /.row -->
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Descrição</th>
                        <th></th>
                    </tr>
                </thead>
                
                <tbody>
                <% @categories.each do |categoria| %>
                    <tr>
                        <td><%= categoria.id %></td>
                        <td><%= categoria.description%></td>
                        <td style = "width: 150px">
                        <%= link_to edit_backoffice_category_path(categoria), class: "btn btn-primary btn-circle" do %>
                             <i class="fa fa-edit"></i>
                        <% end %>
                            <button type="button" disabled="disabled" class="btn btn-danger btn-circle"><i class="fa fa-times"></i>
                            </button>
                        </td>
                    </tr>                  
                <% end %>                    
                </tbody>
            </table>
        </div>
        <div class="row">
            <%= link_to new_backoffice_category_path, class: "btn btn-success btn-circle pull-right" do %>
                <i class="fa fa-plus"></i>
            <% end %>
        </div>

    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->>
 

app/views/backoffice/categories/new.html.erb
<%= render partial: "backoffice/categories/shared/form", locals: {action: "Nova categoria"} %>

app/views/backoffice/categories/shared/_form.html.erb
<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Categoria</h1>
                <% if @category.errors.any? %>
                <div class="alert alert-danger">
                    <ul>
                        <% @category.errors.full_messages.each do |message|%>
                        <li><%= message %></li>
                        <% end %>  
                    </ul>                  
                </div>
                <% end %>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        
<div class="panel panel-default">
            <div class="panel-heading">
                <%= action %>
            </div>
            <div class="panel-body">
                <%= form_for ([:backoffice, @category]) do |f| %>
                    <div class="form-group">
                        <label>Descrição</label>
                        <%= f.text_field :description , class:"form-control" , placeholder:"Ex: Animais/Pet" %>
                    </div>

                    <button type="submit" class="btn btn-default">Cadastrar</button>              
                <% end %>
            </div>
            <!-- /.panel-body -->
        </div>
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->>

app/views/backoffice/dashboard/index.html.erb
    <!-- Page Content -->
    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Blank</h1>
                </div>
                <!-- /.col-lg-12 -->
                <a id= "btn-show" class="btn btn-success btn-circle pull-right">
                     <i class="fa fa-plus"></i>
                </a>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /#page-wrapper -->
<script>
$(function(){
    $("#btn-show").click(function(){
        Swal.fire({
            title: 'Selecione o Ano Base',
            input: 'select',
            inputOptions: {
                '2017': '2017',
                '2018': '2018'
                
            },
            showCancelButton: true,
            cancelButtonText: 'Cancelar'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        type: 'POST',
                        url: '/backoffice/dashboard/set_ano',
                        data: {
                            ano: result.value
                        }
                    }).done(function(e){
                        Swal.fire({
                            type: 'success',
                            title: e['msg'],
                            showConfirmButton: false,
                            timer: 1500
                        });
                    });
                }
            });
        });
    });

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minhatarefa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/backoffice.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Minhatarefa</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag    'backoffice', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'backoffice', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/sweetalert2@8' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/notify/0.4.2/notify.js' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js' %>

    

    <!--<%= javascript_include_tag 'https://unpkg.com/sweetalert/dist/sweetalert.min.js' %> -->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
  <div id="wrapper">
    <%= render partial: "layouts/backoffice_shared/navigation" %>
    <%= yield %>  
  </div>

  <% if alert %>
    <%= javascript_tag "Swal.fire('Atenção!', '#{alert}'  , 'success');" %>        
  <% end %>   
</body>

</html>

app/views/layouts/backoffice_devise.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Minhatarefa</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag    'backoffice', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'backoffice', 'data-turbolinks-track': 'reload' %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <%= yield %>  
</body>

</html>

app/views/layouts/backoffice_shared/_navigation.html.erb
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.html">SB Admin v2.0</a>
        </div>
        <!-- /.navbar-header -->

        <ul class="nav navbar-top-links navbar-right">
        <li><%= current_admin.email %></li>

            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li>
                    <%= link_to destroy_admin_session_path, method: :delete do %>
                         <i class="fa fa-sign-out fa-fw"></i> 
                         Logout                    
                    <%end%>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
        <!-- /.navbar-top-links -->
        <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li class="sidebar-search">
                    <div class="input-group custom-search-form">
                        <input type="text" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                    <!-- /input-group -->
                </li>
                <li>
                    <%= link_to backoffice_path do %>
                        <i class="fa fa-dashboard fa-fw"></i> Dashboard
                    <% end %>   
                </li>      
                <li>
                    <%= link_to backoffice_categories_path do %>
                        <i class="fa fa-th-list fa-fw"></i> Categorias
                    <% end %>            
                </li>   
                <li>
                    <%= link_to backoffice_admins_path do %>
                        <i class="fa fa-users fa-fw"></i> Administradores
                    <% end %>            
                </li>             
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Minhatarefa</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag    'site', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'site', 'data-turbolinks-track': 'reload' %>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
  <%= render partial: "layouts/site_shared/navigation" %>
  <%= yield %>
  <%= render partial: "layouts/site_shared/footer" %>
</body>

</html>

app/views/layouts/site_shared/_footer.html.erb
<!-- /.container -->

<div class="container">

    <hr>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Your Website 2019</p>
            </div>
        </div>
    </footer>
</div>

app/views/layouts/site_shared/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Start Bootstrap</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/members/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>